### ISSUE TITLE
errors in sbt/assembly

### ISSUE THREAD

**Issue by willli666** [moscowart/real-time-recommender#1]
Hello!  Thanks for sharing this project. I'm seeing the following errors/warning when doing assembly in sbt.  It looks like I'm missing some library but the jar is built and all tests are passed.

Are these expected? Any advice on what I might miss? 

`
> assembly
Initialize EmbeddedCassandra singleton.
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[info] Starting Cassandra in embedded mode with default configuration.
[info] Compiling 1 Scala source to /home/willapollobox_gmail_com/real-time-recommender/target/classes...
no libsigar-amd64-linux.so in java.library.path
org.hyperic.sigar.SigarException: no libsigar-amd64-linux.so in java.library.path
	at org.hyperic.sigar.Sigar.loadLibrary(Sigar.java:172)
	at org.hyperic.sigar.Sigar.<clinit>(Sigar.java:100)
	at org.apache.cassandra.utils.SigarLibrary.<init>(SigarLibrary.java:45)
	at org.apache.cassandra.service.StartupChecks$5.execute(StartupChecks.java:178)
	at org.apache.cassandra.service.StartupChecks.verify(StartupChecks.java:103)
	at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:162)
	at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:511)
	at org.cassandraunit.utils.EmbeddedCassandraServerHelper$1.run(EmbeddedCassandraServerHelper.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[warn] Multiple main classes detected.  Run 'show discoveredMainClasses' to see the list
`

**Comment by artmoskvin** [comment]
Hi @willli666. Thanks for checking in. This library is required for embedded Cassandra for testing. There are different ways to install it depending on your OS.
