### ISSUE TITLE
Cassandra Cannot connect

### ISSUE THREAD

**Issue by willli666** [moscowart/real-time-recommender#2]
The docker starts with this error msg in log
```
09:00:33.878 [main] DEBUG com.datastax.driver.core.ControlConnection - [Control connection] error on localhost/127.0.0.1:9042 connection, no more host to try
com.datastax.driver.core.exceptions.TransportException: [localhost/127.0.0.1] Cannot connect
        at com.datastax.driver.core.Connection$1.operationComplete(Connection.java:158)
        at com.datastax.driver.core.Connection$1.operationComplete(Connection.java:141)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:680)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:603)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:563)
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:424)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:276)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:292)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:528)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection refused: localhost/127.0.0.1:9042
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
        at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:224)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:289)
        ... 6 common frames omitted
09:00:33.879 [main] DEBUG com.datastax.driver.core.Cluster - Shutting down

```
However, my casandra is indeed running on localhost 9042.  I can run cqlsh on command line to see the following
```
$ cqlsh
Connected to Test Cluster at 127.0.0.1:9042.
[cqlsh 5.0.1 | Cassandra 3.6 | CQL spec 3.4.2 | Native protocol v4]
Use HELP for help.
```

So I'm wondering what might cause this issue? Does the dependency in the docker need to be updated?

**Comment by artmoskvin** [comment]
Hi @willli666. I'm sorry but I could not reproduce your error. I tried Cassandra 3.11.4 with default parameters and I set `val CASSANDRA_HOST = "localhost"` in `config.Config`.

**Comment by willli666** [comment]
@moscowart  I upgraded my Cassandra to 3.11.4 but still had this issue. Can you share your OS version?  I'm running it on ubuntu 18 on google cloud.

**Comment by willli666** [comment]
In the tests, the logs prints about connections to 127.0.0.1:9142 and the tests all passed.  But my Cassandra's port is 9042. So is the test connecting to the local Cassandra or not?

Thanks for helping with my newbie questions

**Comment by artmoskvin** [comment]
@willli666 macOS 10.14.5. In tests, there's embedded Cassandra. It is launched before tests and shut down after. I think there's some misconfiguration between networking on your instance and Cassandra config.

**Comment by artmoskvin** [comment]
@willli666 oh wait! I know what the problem is. Docker containers can't see host ports because they are running in a different network. You can either run the application without docker container, simply by `sbt run` or `java -cp recommender-processor-assembly-1.0.jar WebServer`, or run Cassandra as a docker container (make sure you use docker-compose so that your containers have the same network).

**Comment by willli666** [comment]
Thanks! I now just run the jar directly and it's working.
